### ISSUE TITLE
Synology. Docker. noob. Dont know how to do it - tried, url doesnt resolve

### ISSUE THREAD

**Issue by cosmic-tiger** [jlesage/docker-filezilla#25]
Hi,
Using the Synology Disk Station. Downloaded latest docker. downlownloaded  latest docker-filezilla.
When starting and browsing to ip address of Disk station, using port 5800, http (or https, no diff), unable to connect.
Some warnings in log: invalid source position for vertical gradient.
Anyway, I don't know what the settings should be ... I have guessed:
General settings tab: second time round, decided to select "execute  higher privilege" to see if it would work,
volume tab: nothing
port settings tab: 5800, 5900
Links tab: nothing
environment tab: a load of settings.
Whatever happens, nothing listening on port 5800 (browser) or 5900 (vnc viewer)

**Comment by jlesage** [comment]
I think that Synology automatically maps port 5800 to a random port.  This mapping is configurable.  For example: 

![](https://www.synology.com/helpfile/help/Docker/18.09/Docker/images/10.png)

In your case, you need a mapping for container port 5800.  Instead of having a local port set to `Auto`, you can set a specific one.

**Comment by cosmic-tiger** [comment]
Yep, this worked, thank you. I've removed the auto, and mapped container ports 5800/5900 to local ports 5801/5901. Nice.
I can see it. Really is very nice -very impressive! Thank you!
