### ISSUE TITLE
Enhancement: Allow changing of internal port numbers

### ISSUE THREAD

**Issue by CallMeTerdFerguson** [jlesage/docker-filezilla#26]
Right now port remapping, as the README points out, is only possible via port redirection on the container itself. While this works fine for a lot of use cases, it breaks down at one that I think is somewhat important, which is when you want to use another, shared container's networking. Specifically, I want to be able to stand this up using my VPN container's networking, but those ports are already in use on that container by another client container (perhaps unsurprisingly, another of your containers, jdownloader). 

It would be nice to be able to remap via environment variables the ports in use. Alternatively, at a minimum, it would be good to alter this container to not use the same ports as your other containers so that they don't cause conflicts if folks are using shared networking via another container.

**Comment by jlesage** [comment]
Yes, configuration of the ports through environment variables is something I plan to do.

**Comment by agrider** [comment]
@jlesage Great, thanks. I was just looking around to see if I could submit a pull, but it looks like much of this config is coming from a base image you use across several of your images, so I'm going to just wait for you to implement since it seems any pull would have ripples across your images. Thanks!

**Comment by jlesage** [comment]
This is now supported with latest image.
